__author__ = 'Pavan'

URL = 'http://newtours.demoaut.com/'
title = 'Welcome: Mercury Tours'
timeout = '3s'
Username = 'Aditya'
Password = 'Test123'
signOn_Page_Title = 'Sign-on: Mercury Tours'
U_FirstName = 'Aditya'
U_LastName = 'Roy'
U_phone = '7501451160'
U_userID = 'aditya.qa14@gmail.com'
U_country = 'INDIA'
U_userName = 'aditya.qa14@gmail.com'
U_password = 'Test123'
U_confirmPassword = 'Test123'
